name: Snapshot Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare mvn configuration
        env:
          MVN_SETTINGS: ${{ secrets.MVN_SETTINGS }}
        run: chmod +x ./dev/deploy-snapshot.sh

      - name: Run tests
        run: mvn install

      - name: Prepare configuration
        run: ./dev/deploy-snapshot.sh
